/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["usermodel_me_032e6906"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update */
        patch: operations["usermodel_update_cf1e1377"];
        trace?: never;
    };
    "/api/kitchen/recipes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recipes */
        get: operations["recipes_list_recipes_5cb8c4d5"];
        put?: never;
        /** Create Recipe */
        post: operations["recipes_create_recipe_545d6bf3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen/recipes/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["recipes_get_recipe_ebdc931a"];
        put?: never;
        post?: never;
        /** Delete Recipe */
        delete: operations["recipes_delete_recipe_3828609d"];
        options?: never;
        head?: never;
        /** Update Recipe */
        patch: operations["recipes_update_recipe_3c8e75d0"];
        trace?: never;
    };
    "/api/kitchen/recipes/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe By Slug */
        get: operations["recipes_get_recipe_by_slug_99c4a273"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen/recipes/drafts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Drafts */
        get: operations["recipedrafts_list_drafts_49f333eb"];
        put?: never;
        /** Create Draft */
        post: operations["recipedrafts_create_draft_03df7e59"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen/recipes/drafts/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["recipedrafts_get_draft_c0e84457"];
        put?: never;
        post?: never;
        /** Delete Draft */
        delete: operations["recipedrafts_delete_draft_5380e48d"];
        options?: never;
        head?: never;
        /** Update Draft */
        patch: operations["recipedrafts_update_draft_ca3901a5"];
        trace?: never;
    };
    "/api/kitchen/recipes/drafts/{uid}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Draft */
        post: operations["recipedrafts_finish_draft_e34804ff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen/ingredients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingredients */
        get: operations["ingredients_list_ingredients_89a2024e"];
        put?: never;
        /** Create Ingredient */
        post: operations["ingredients_create_ingredient_d2066c21"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen/units/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Units */
        get: operations["units_list_units_2166138d"];
        put?: never;
        /** Create Unit */
        post: operations["units_create_unit_9ec68de1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen/appliances/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Appliances
         * @description List appliances. Can be filtered by manufacturer and/or type.
         */
        get: operations["appliances_list_appliances_aaf1896a"];
        put?: never;
        /** Create Appliance */
        post: operations["appliances_create_appliance_4b0d6b23"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/{backend}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Social Login
         * @description Authenticates user via social network and returns JWT tokens.
         */
        post: operations["users_api_auth_social_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh an access token using a refresh token.
         */
        post: operations["users_api_auth_refresh_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** UserSchema */
        UserSchema: {
            /**
             * Uid
             * Format: uuid7
             * @description Unique identifier
             */
            uid: string;
            /** Email */
            email: string;
            /** Handler */
            handler?: string | null;
            /** Username */
            username?: string | null;
            /** Avatar */
            avatar?: string | null;
        };
        /** UserUpdateSchema */
        UserUpdateSchema: {
            /** Handler */
            handler?: string | null;
            /** Username */
            username?: string | null;
            /** Avatar */
            avatar?: string | null;
        };
        /** AuthorSchema */
        AuthorSchema: {
            /**
             * Uid
             * Format: uuid7
             * @description Unique identifier
             */
            uid: string;
            /** Username */
            username?: string | null;
            /** Handler */
            handler?: string | null;
        };
        /** RecipeShortSchema */
        RecipeShortSchema: {
            /**
             * Uid
             * Format: uuid7
             * @description Unique identifier
             */
            uid: string;
            author?: components["schemas"]["AuthorSchema"] | null;
            /** Slug */
            slug?: string | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Image */
            image?: string | null;
            /**
             * Visibility
             * @default PRIVATE
             */
            visibility: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** IngredientInRecipeSchema */
        IngredientInRecipeSchema: {
            /**
             * Uid
             * Format: uuid7
             * @description Unique identifier
             */
            uid: string;
            ingredient: components["schemas"]["IngredientSchema"];
            unit?: components["schemas"]["UnitSchema"] | null;
            /** Quantity */
            quantity?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** IngredientSchema */
        IngredientSchema: {
            /**
             * Uid
             * Format: uuid7
             * @description Unique identifier
             */
            uid: string;
            /** Name */
            name: string;
        };
        /** InstructionSchema */
        InstructionSchema: {
            /**
             * Uid
             * Format: uuid7
             * @description Unique identifier
             */
            uid: string;
            /** Step */
            step: number;
            /** Description */
            description: string;
            /** Timer */
            timer?: number | null;
        };
        /** RecipeSchema */
        RecipeSchema: {
            /**
             * Uid
             * Format: uuid7
             * @description Unique identifier
             */
            uid: string;
            /**
             * Ingredients
             * @default []
             */
            ingredients: components["schemas"]["IngredientInRecipeSchema"][];
            /**
             * Instructions
             * @default []
             */
            instructions: components["schemas"]["InstructionSchema"][];
            author?: components["schemas"]["AuthorSchema"] | null;
            /** Slug */
            slug?: string | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Image */
            image?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Visibility
             * @default PRIVATE
             */
            visibility: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Is Draft
             * @default true
             */
            is_draft: boolean;
        };
        /** UnitSchema */
        UnitSchema: {
            /** Uid */
            uid?: string | null;
            /** Abbreviation */
            abbreviation: string;
            /** Name */
            name: string;
        };
        /** IngredientInRecipeCreateSchema */
        IngredientInRecipeCreateSchema: {
            /**
             * Ingredient Uid
             * Format: uuid
             */
            ingredient_uid: string;
            /** Unit Uid */
            unit_uid?: string | null;
            /** Quantity */
            quantity?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** InstructionCreateSchema */
        InstructionCreateSchema: {
            /** Step */
            step: number;
            /** Description */
            description: string;
            /** Timer */
            timer?: number | null;
        };
        /** RecipeCreateSchema */
        RecipeCreateSchema: {
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Image */
            image?: string | null;
            /** Notes */
            notes?: string | null;
            /** Instructions */
            instructions: components["schemas"]["InstructionCreateSchema"][];
            /** Ingredients */
            ingredients: components["schemas"]["IngredientInRecipeCreateSchema"][];
            /** @default PRIVATE */
            visibility: components["schemas"]["Visibility"];
        };
        /**
         * Visibility
         * @enum {string}
         */
        Visibility: "PUBLIC" | "FRIENDS" | "PRIVATE";
        /** DraftSchema */
        DraftSchema: {
            /** Uid */
            uid?: string | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Image */
            image?: string | null;
            /** Notes */
            notes?: string | null;
            /** Instructions */
            instructions?: components["schemas"]["InstructionCreateSchema"][] | null;
            /** Ingredients */
            ingredients?: components["schemas"]["IngredientInRecipeCreateSchema"][] | null;
            /** @default PRIVATE */
            visibility: components["schemas"]["Visibility"];
        };
        /** IngredientCreateSchema */
        IngredientCreateSchema: {
            /** Name */
            name: string;
            /** Image */
            image?: string | null;
        };
        /** ApplianceSchema */
        ApplianceSchema: {
            manufacturer: components["schemas"]["ManufacturerSchema"];
            type: components["schemas"]["ApplianceTypeSchema"];
            /** Uid */
            uid?: string | null;
            /** Model */
            model: string;
        };
        /** ApplianceTypeSchema */
        ApplianceTypeSchema: {
            /** Uid */
            uid?: string | null;
            /** Name */
            name: string;
        };
        /** ManufacturerSchema */
        ManufacturerSchema: {
            /** Uid */
            uid?: string | null;
            /** Name */
            name: string;
        };
        /** ApplianceCreateSchema */
        ApplianceCreateSchema: {
            /** Model */
            model: string;
            /**
             * Manufacturer Uid
             * Format: uuid
             */
            manufacturer_uid: string;
            /**
             * Type Uid
             * Format: uuid
             */
            type_uid: string;
        };
        /** AuthResponseSchema */
        AuthResponseSchema: {
            user: components["schemas"]["UserSchema"];
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
        };
        /** SocialAuthSchema */
        SocialAuthSchema: {
            /** Code */
            code: string;
            /** Redirect Uri */
            redirect_uri: string;
        };
        /** TokenRefreshResponseSchema */
        TokenRefreshResponseSchema: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
        };
        /** TokenRefreshSchema */
        TokenRefreshSchema: {
            /** Refresh Token */
            refresh_token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    usermodel_me_032e6906: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSchema"];
                };
            };
        };
    };
    usermodel_update_cf1e1377: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSchema"];
                };
            };
        };
    };
    recipes_list_recipes_5cb8c4d5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeShortSchema"][];
                };
            };
        };
    };
    recipes_create_recipe_545d6bf3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreateSchema"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    recipes_get_recipe_ebdc931a: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSchema"];
                };
            };
        };
    };
    recipes_delete_recipe_3828609d: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recipes_update_recipe_3c8e75d0: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreateSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSchema"];
                };
            };
        };
    };
    recipes_get_recipe_by_slug_99c4a273: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSchema"];
                };
            };
        };
    };
    recipedrafts_list_drafts_49f333eb: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSchema"][];
                };
            };
        };
    };
    recipedrafts_create_draft_03df7e59: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSchema"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    recipedrafts_get_draft_c0e84457: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSchema"];
                };
            };
        };
    };
    recipedrafts_delete_draft_5380e48d: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recipedrafts_update_draft_ca3901a5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSchema"];
                };
            };
        };
    };
    recipedrafts_finish_draft_e34804ff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingredients_list_ingredients_89a2024e: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientSchema"][];
                };
            };
        };
    };
    ingredients_create_ingredient_d2066c21: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientCreateSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientSchema"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientSchema"];
                };
            };
        };
    };
    units_list_units_2166138d: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitSchema"][];
                };
            };
        };
    };
    units_create_unit_9ec68de1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitSchema"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitSchema"];
                };
            };
        };
    };
    appliances_list_appliances_aaf1896a: {
        parameters: {
            query?: {
                manufacturer_uid?: string | null;
                type_uid?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplianceSchema"][];
                };
            };
        };
    };
    appliances_create_appliance_4b0d6b23: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplianceCreateSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplianceSchema"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplianceSchema"];
                };
            };
        };
    };
    users_api_auth_social_login: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialAuthSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    users_api_auth_refresh_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefreshResponseSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
